### ISSUE TITLE
anaconda cloud package?

### ISSUE THREAD

**Issue by fcakyon** [zopefoundation/DateTime#22]
Hello,

DateTime is a great package however only [pypi distibution](https://pypi.org/project/DateTime/) is present and it is not possible for anyone to use this package in a project if they want to to publish their project to [anaconda cloud](https://anaconda.org/). Do you have any intentions of publishing this project to anaconda cloud?

**Comment by dataflake** [comment]
PyPI is the only official distribution channel for Python packages that I am aware of that is supported by all standard Python packaging tools. There are no plans to support any others.

**Comment by fcakyon** [comment]
[Anaconda is the preferred distribution channel for machine learning/deep learning related packages](https://pytorch.org/get-started/locally/#linux-package-manager). Thus machine learning projects tend to publish both PYPI and Conda packages.

**Comment by dataflake** [comment]
As I wrote on the PR you created, this is the first time ever that anyone has asked about this in the 20+ years that I have been involved in Zope development. This may be interesting if there is sufficient demand from a lot of people, but until then we won't make plans to add support for other repositories.
