### ISSUE TITLE
Show badges

### ISSUE THREAD

**Issue by jugmac00** [zopefoundation/DateTime#23]
e.g. for Travis build and more...

**Comment by jugmac00** [comment]
This is not that easy as it looked like.

The `src/DateTime/DateTime.txt` is not only used as a README, but also for doctests.

Moving it to the root directory and updating the path for `DocFileSuite` breaks all doctests with following error message
```
Test-module import failures:
Module: DateTime.tests.test_datetime
ValueError: Module-relative files may not have absolute paths
```

Duplicating DateTime.txt is also no option.

Using a minimal README also does not seem right, as then on PyPi there won't be much info any more.

Also, I don't think rewriting doctests is time well spent.

Are there any opinions about what to do? Maybe we just leave it as is, although it would be pretty nice to have a good overview over supported packages and build status when one visits the GitHub repository.

**Comment by icemac** [comment]
You should go the same route as we did in https://github.com/zopefoundation/zc.beforestorage/pull/3: split the file and put the parts needed into required places but put everything together in `long_description` of `setup.py`.

**Comment by jugmac00** [comment]
Ah right - thanks @icemac - totally missed this option!
