### ISSUE TITLE
asdatetime regression in DateTime 4.7 for Python 2.7 

### ISSUE THREAD

**Issue by mauritsvanrees** [zopefoundation/DateTime#47]
When using the latest DateTime in Plone 5.2 on Python 2.7, one test fails. See https://github.com/plone/Products.ATContentTypes/issues/69
Note that this is a package that only works on Python 2.7.

The regression is caused by the changes in 4.7 from PR #42. I am preparing a PR. Looks like it only goes wrong in Python 2, not Python 3.

Small problem: @icemac has just changed DateTime master to be for Python 3 only.
So I have created branch 4.x from right before his changes. I will make my PR against that new branch.

**Comment by dataflake** [comment]
Fixed in release 4.9
